# Dota 2 Analytics API: полный пример запросов

Ноутбук дергает все публичные endpoints локального FastAPI-сервиса, обновляет игрока, ждет job и выводит статистику в таблицы.

Перед запуском убедись, что API поднят, например:

```powershell
$env:DATABASE_URL='sqlite+pysqlite:///./dev.sqlite'
python -m uvicorn app.main:app --host 127.0.0.1 --port 8000
```

Swagger: http://127.0.0.1:8000/docs

In [1]:
from __future__ import annotations

import json
import os
import time
from datetime import datetime
from pathlib import Path
from typing import Any

import httpx
from dotenv import load_dotenv
from IPython.display import JSON, Markdown, display

try:
    import pandas as pd
except ImportError:
    pd = None

load_dotenv()

API_BASE = os.getenv("API_BASE", "http://127.0.0.1:8000").rstrip("/")
ACCOUNT_ID = int(os.getenv("ACCOUNT_ID", "175966938"))

API_BASE, ACCOUNT_ID

('http://127.0.0.1:8000', 175966938)

In [2]:
def api_request(
    method: str,
    path: str,
    *,
    params: dict[str, Any] | None = None,
    json_body: dict[str, Any] | None = None,
    allow_error: bool = False,
    timeout: float = 30.0,
) -> tuple[int, Any]:
    """Call local FastAPI service and return (status_code, json_or_text)."""
    url = f"{API_BASE}{path}"
    with httpx.Client(timeout=timeout) as client:
        response = client.request(method, url, params=params, json=json_body)

    try:
        payload = response.json()
    except ValueError:
        payload = response.text

    if not allow_error:
        response.raise_for_status()
    return response.status_code, payload


def as_table(data: Any, *, max_rows: int = 100):
    if pd is None:
        display(JSON(data))
        return None
    if isinstance(data, list):
        frame = pd.json_normalize(data)
    elif isinstance(data, dict):
        frame = pd.json_normalize(data)
    else:
        display(data)
        return None
    display(frame.head(max_rows))
    return frame


def show_json(title: str, data: Any):
    display(Markdown(f"## {title}"))
    if isinstance(data, dict | list):
        display(JSON(data, expanded=False))
        return
    text = str(data).replace("```", "'''")
    display(Markdown(f"```text\n{text}\n```"))


def show_table(title: str, data: Any, *, max_rows: int = 100):
    display(Markdown(f"## {title}"))
    return as_table(data, max_rows=max_rows)


def duration_label(seconds: int | None) -> str | None:
    if seconds is None:
        return None
    minutes, secs = divmod(int(seconds), 60)
    return f"{minutes}:{secs:02d}"


def kda(kills: int, deaths: int, assists: int) -> float:
    return round((kills + assists) / max(1, deaths), 2)

## 1. Healthcheck

In [3]:
status, health = api_request("GET", "/health", allow_error=True)
show_json(f"GET /health -> {status}", health)

if status != 200:
    raise RuntimeError(f"API is not healthy or not running at {API_BASE}: {health}")

## GET /health -> 200

## 2. Каталог ачивок

`GET /v1/achievements` возвращает все определения ачивок без привязки к игроку.

In [4]:
status, achievement_catalog = api_request("GET", "/v1/achievements")
catalog_df = show_table(f"GET /v1/achievements -> {status}", achievement_catalog, max_rows=200)

if pd is not None:
    display(Markdown("### Ачивки по категориям"))
    display(catalog_df.groupby(["category", "tier"]).size().reset_index(name="count"))

## GET /v1/achievements -> 200

,id,title,description,category,tier,progress,target,progressPercent,unlocked,unavailable,unlockedAt
0,marathon_day,Marathon Day,Play 5+ games in one day.,activity,silver,0.0,5.0,0.0,False,False,None
1,returning_player,Returning Player,Play after a 14+ day break.,activity,bronze,0.0,1.0,0.0,False,False,None
2,weekly_grinder,Weekly Grinder,Play 10+ games in 7 days.,activity,bronze,0.0,10.0,0.0,False,False,None
3,chaos_enjoyer,Chaos Enjoyer,Play 3 games in a row lasting 45+ minutes.,fun,bronze,0.0,3.0,0.0,False,False,None
4,glass_cannon,Glass Cannon,Deal 35k+ hero damage with 10+ deaths.,fun,bronze,0.0,1.0,0.0,False,False,None
5,alchemist_chemical_salary,Забрал пенсию у бабки,Выиграй 10 игр подряд на Alchemist.,hero_flavor,silver,0.0,10.0,0.0,False,False,None
6,anti_mage_afk_forest,"АФК лес, потом GG проебали",Выиграй 10 игр подряд на Anti-Mage.,hero_flavor,gold,0.0,10.0,0.0,False,False,None
7,arc_warden_two_accounts,Два аккаунта в одной игре,Выиграй 10 игр подряд на Arc Warden.,hero_flavor,gold,0.0,10.0,0.0,False,False,None
8,axe_spin_doctor,Вертушка судьбы,Выиграй 10 игр подряд на Axe.,hero_flavor,silver,0.0,10.0,0.0,False,False,None
9,broodmother_real_estate,Риэлтор паутины,Выиграй 10 игр подряд на Broodmother.,hero_flavor,gold,0.0,10.0,0.0,False,False,None
10,chen_zoo_director,Директор зоопарка,Выиграй 5 игр подряд на Chen.,hero_flavor,gold,0.0,5.0,0.0,False,False,None
11,clinkz_tower_arson,Поджог недвижимости,Сделай 10k+ tower damage на Clinkz.,hero_flavor,gold,0.0,10000.0,0.0,False,False,None
12,crystal_maiden_arcane_on_boots,Аркана на тапках,Выиграй 10 игр подряд на Crystal Maiden.,hero_flavor,silver,0.0,10.0,0.0,False,False,None
13,dazzle_no_one_dies,"Никто не умер, я сказал",Выиграй 5 игр на Dazzle с 3 или меньше смертями.,hero_flavor,silver,0.0,5.0,0.0,False,False,None
14,earthshaker_echo_couch,Эхо с дивана,Выиграй 10 игр подряд на Earthshaker.,hero_flavor,silver,0.0,10.0,0.0,False,False,None
15,faceless_void_chrono_lawyer,Хуйсос безглазый,Выиграй 10 игр подряд на Faceless Void.,hero_flavor,silver,0.0,10.0,0.0,False,False,None
16,huskar_low_hp_lifestyle,Жизнь на красном HP,Выиграй 10 игр подряд на Huskar.,hero_flavor,silver,0.0,10.0,0.0,False,False,None
17,invoker_piano_without_notes,Пианист без нот,Выиграй 10 игр подряд на Invoker.,hero_flavor,gold,0.0,10.0,0.0,False,False,None
18,io_ball_of_anxiety,Шар тревожности,Выиграй 5 игр подряд на Io.,hero_flavor,gold,0.0,5.0,0.0,False,False,None
19,juggernaut_spin_to_win,Крутилка без мыслей,Выиграй 10 игр подряд на Juggernaut.,hero_flavor,silver,0.0,10.0,0.0,False,False,None
20,lion_finger_explained,Палец объяснил,Выиграй 10 игр подряд на Lion.,hero_flavor,silver,0.0,10.0,0.0,False,False,None
21,meepo_family_contract,Мобилизация чурок,Выиграй 5 игр подряд на Meepo.,hero_flavor,gold,0.0,5.0,0.0,False,False,None
22,ogre_magi_ludik_ebanny,Лудик ебанный,Сделай 30k+ hero damage на Ogre Magi.,hero_flavor,gold,0.0,30000.0,0.0,False,False,None
23,phantom_assassin_crit_to_morale,Крит по морали,Выиграй 10 игр подряд на Phantom Assassin.,hero_flavor,gold,0.0,10.0,0.0,False,False,None
24,pudge_hookaholic,Хукоголик,Выиграй 10 игр подряд на Pudge.,hero_flavor,gold,0.0,10.0,0.0,False,False,None
25,riki_where_is_detection,Где сентри?,Выиграй 10 игр подряд на Riki.,hero_flavor,silver,0.0,10.0,0.0,False,False,None
26,shadow_fiend_zxc_ministry,Неформал дед инсайд,Выиграй 10 игр подряд на Shadow Fiend.,hero_flavor,gold,0.0,10.0,0.0,False,False,None
27,sniper_balcony_grandpa,Дед с хуем на балконе,Выиграй 10 игр подряд на Sniper.,hero_flavor,silver,0.0,10.0,0.0,False,False,None
28,storm_spirit_mana_credit,Мана в кредит,Выиграй 10 игр подряд на Storm Spirit.,hero_flavor,gold,0.0,10.0,0.0,False,False,None
29,techies_son_of_shahed,Сын шахеда,Выиграй 10 игр подряд на Techies. Минное поле ...,hero_flavor,legendary,0.0,10.0,0.0,False,False,None
30,tinker_button_maniac,Кнопочный душнила,Выиграй 10 игр подряд на Tinker.,hero_flavor,gold,0.0,10.0,0.0,False,False,None
31,ursa_roshan_landlord,Хозяин Рошпита,Выиграй 10 игр подряд на Ursa.,hero_flavor,silver,0.0,10.0,0.0,False,False,None
32,witch_doctor_maledict_enjoyer,Маледикт терапевт,Выиграй 10 игр подряд на Witch Doctor.,hero_flavor,silver,0.0,10.0,0.0,False,False,None
33,zeus_damage_cloud,Облако с претензией,Сделай 45k+ hero damage на Zeus.,hero_flavor,gold,0.0,45000.0,0.0,False,False,None
34,cursed_breaker,Cursed Breaker,Win on a hero after 3 losses in a row.,hero_mastery,gold,0.0,1.0,0.0,False,False,None
35,hero_loyalist,Hero Loyalist,Play one hero 25+ times in the last 100 games.,hero_mastery,silver,0.0,25.0,0.0,False,False,None
36,hero_spammer,Hero Spammer,Play one hero 10+ times in the last 30 games.,hero_mastery,bronze,0.0,10.0,0.0,False,False,None
37,signature_hero,Signature Hero,10+ games and 60%+ winrate on one hero.,hero_mastery,gold,0.0,1.0,0.0,False,False,None
38,wide_pool,Wide Pool,Win with 10 different heroes.,hero_mastery,silver,0.0,10.0,0.0,False,False,None
39,clean_game,Clean Game,Win with <=2 deaths and 50%+ kill participation.,performance,gold,0.0,1.0,0.0,False,False,None
40,damage_dealer,Damage Dealer,Deal 40k+ hero damage.,performance,gold,0.0,40000.0,0.0,False,False,None
41,deathless_win,Deathless Win,Win with 0 deaths.,performance,silver,0.0,1.0,0.0,False,False,None
42,farming_machine,Farming Machine,Reach 700+ GPM.,performance,silver,0.0,700.0,0.0,False,False,None
43,healer,Healer,Heal 10k+ hero HP in one game.,performance,silver,0.0,10000.0,0.0,False,False,None
44,kda_10,KDA Monster,Reach 10+ KDA in a game.,performance,silver,0.0,10.0,0.0,False,False,None
45,kda_5,KDA Machine,Reach 5+ KDA in a game.,performance,bronze,0.0,5.0,0.0,False,False,None
46,support_engine,Support Engine,Get 25+ assists in one game.,performance,silver,0.0,25.0,0.0,False,False,None
47,tower_melter,Tower Melter,Deal 8k+ tower damage.,performance,gold,0.0,8000.0,0.0,False,False,None
48,xp_machine,XP Machine,Reach 800+ XPM.,performance,silver,0.0,800.0,0.0,False,False,None
49,carry_core,Carry Core,Infer carry role and high farm score.,role,silver,0.0,1.0,0.0,False,False,None
50,flex_player,Flex Player,Play 3+ inferred roles in 50 games.,role,gold,0.0,3.0,0.0,False,False,None
51,mid_pressure,Mid Pressure,Infer mid role and high fighting score.,role,silver,0.0,1.0,0.0,False,False,None
52,offlane_impact,Offlane Impact,Infer offlane role and high impact/survival.,role,silver,0.0,1.0,0.0,False,False,None
53,support_brain,Support Brain,Infer support role and high utility.,role,silver,0.0,1.0,0.0,False,False,None
54,clutch_late_game,Late Game Clutch,Win a game lasting 50+ minutes.,win_form,silver,0.0,1.0,0.0,False,False,None
55,hot_streak_10,Hot Streak X,Win 10 games in a row.,win_form,gold,0.0,10.0,0.0,False,False,None
56,hot_streak_3,Hot Streak III,Win 3 games in a row.,win_form,bronze,0.0,3.0,0.0,False,False,None
57,hot_streak_5,Hot Streak V,Win 5 games in a row.,win_form,silver,0.0,5.0,0.0,False,False,None
58,tilt_resistant,Tilt Resistant,Win after 3 losses in a row.,win_form,silver,0.0,1.0,0.0,False,False,None

### Ачивки по категориям

        category       tier  count
0       activity     bronze      2
1       activity     silver      1
2            fun     bronze      2
3    hero_flavor       gold     15
4    hero_flavor  legendary      1
5    hero_flavor     silver     13
6   hero_mastery     bronze      1
7   hero_mastery       gold      2
8   hero_mastery     silver      2
9    performance     bronze      1
10   performance       gold      3
11   performance     silver      6
12          role       gold      1
13          role     silver      4
14      win_form     bronze      1
15      win_form       gold      1
16      win_form     silver      3

## 3. Refresh игрока

`POST /v1/players/{account_id}/refresh` ставит фоновую job. Если сработал cooldown, ноутбук продолжит читать уже сохраненные данные.

In [5]:
refresh_path = f"/v1/players/{ACCOUNT_ID}/refresh"
status, refresh_response = api_request("POST", refresh_path, allow_error=True, timeout=60)
show_json(f"POST {refresh_path} -> {status}", refresh_response)

job = None
if status == 202:
    job = refresh_response
elif status == 429:
    display(Markdown(f"Cooldown: `{refresh_response.get('detail', refresh_response)}`. Используем сохраненную статистику."))
else:
    raise RuntimeError(f"Refresh failed: HTTP {status}: {refresh_response}")

job

## POST /v1/players/175966938/refresh -> 202

{'id': 'cdc2fc1b-1d9d-4403-a1eb-b085f306d75a',
 'accountId': 175966938,
 'status': 'queued',
 'message': None,
 'createdAt': '2026-07-09T20:45:24',
 'startedAt': None,
 'finishedAt': None}

In [6]:
job_status_history = []

if job:
    job_id = job["id"]
    job_path = f"/v1/jobs/{job_id}"
    for _ in range(90):
        status, current_job = api_request("GET", job_path, allow_error=True)
        job_status_history.append(current_job)
        if current_job.get("status") in {"done", "failed"}:
            break
        time.sleep(2)

    show_table(f"GET {job_path} polling", job_status_history)
    if job_status_history[-1].get("status") != "done":
        raise RuntimeError(f"Refresh job did not finish successfully: {job_status_history[-1]}")
else:
    display(Markdown("Refresh job не создавалась из-за cooldown."))

## GET /v1/jobs/cdc2fc1b-1d9d-4403-a1eb-b085f306d75a polling

,id,accountId,status,message,createdAt,startedAt,finishedAt
0,cdc2fc1b-1d9d-4403-a1eb-b085f306d75a,175966938,failed,STRATZ GraphQL errors: [{'message': 'You have ...,2026-07-09T20:45:24,2026-07-09T20:45:24.397848,2026-07-09T20:45:25.899345

RuntimeError: Refresh job did not finish successfully: {'id': 'cdc2fc1b-1d9d-4403-a1eb-b085f306d75a', 'accountId': 175966938, 'status': 'failed', 'message': "STRATZ GraphQL errors: [{'message': 'You have surpassed the maximum take value of :  100'}]", 'createdAt': '2026-07-09T20:45:24', 'startedAt': '2026-07-09T20:45:24.397848', 'finishedAt': '2026-07-09T20:45:25.899345'}

## 4. Забираем все player endpoints одним блоком

In [7]:
endpoint_specs = {
    "summary": ("GET", f"/v1/players/{ACCOUNT_ID}/summary", None),
    "breakdowns": ("GET", f"/v1/players/{ACCOUNT_ID}/breakdowns", None),
    "matches_20": ("GET", f"/v1/players/{ACCOUNT_ID}/matches", {"limit": 20}),
    "matches_100": ("GET", f"/v1/players/{ACCOUNT_ID}/matches", {"limit": 100}),
    "heroes": ("GET", f"/v1/players/{ACCOUNT_ID}/heroes", None),
    "hero_global_winrates": ("GET", "/v1/heroes/winrates", {"limit": 50, "min_matches": 10000, "order_by": "winRate"}),
    "hero_builds_ogre_magi": ("GET", "/v1/heroes/84/builds", {"limit": 10, "min_matches": 1000, "match_limit": 10000}),
    "achievements_all": ("GET", f"/v1/players/{ACCOUNT_ID}/achievements", None),
    "achievements_unlocked": ("GET", f"/v1/players/{ACCOUNT_ID}/achievements", {"unlocked": "true"}),
    "achievements_locked": ("GET", f"/v1/players/{ACCOUNT_ID}/achievements", {"unlocked": "false"}),
    "rating": ("GET", f"/v1/players/{ACCOUNT_ID}/rating", None),
    "style_100": ("GET", f"/v1/players/{ACCOUNT_ID}/style", {"limit": 100}),
    "leaderboard": ("GET", "/v1/leaderboard", {"metric": "overall", "limit": 50}),
}

api_snapshot: dict[str, Any] = {
    "generatedAt": datetime.utcnow().isoformat(timespec="seconds") + "Z",
    "apiBase": API_BASE,
    "accountId": ACCOUNT_ID,
    "health": health,
    "achievement_catalog": achievement_catalog,
    "refresh": refresh_response,
    "jobHistory": job_status_history,
    "responses": {},
}

endpoint_statuses = []
for name, (method, path, params) in endpoint_specs.items():
    status, payload = api_request(method, path, params=params, allow_error=True)
    api_snapshot["responses"][name] = payload
    endpoint_statuses.append({
        "name": name,
        "method": method,
        "path": path,
        "params": params or {},
        "status": status,
        "items": len(payload) if isinstance(payload, list) else 1,
    })

show_table("Статусы всех API endpoints", endpoint_statuses)

C:\Users\Богдан\AppData\Local\Temp\ipykernel_39912\1414671534.py:18: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  "generatedAt": datetime.utcnow().isoformat(timespec="seconds") + "Z",

## Статусы всех API endpoints

,name,method,path,status,items,params.limit,params.min_matches,params.order_by,params.match_limit,params.unlocked,params.metric
0,summary,GET,/v1/players/175966938/summary,200,1,NaN,NaN,NaN,NaN,NaN,NaN
1,breakdowns,GET,/v1/players/175966938/breakdowns,200,1,NaN,NaN,NaN,NaN,NaN,NaN
2,matches_20,GET,/v1/players/175966938/matches,200,20,20.0,NaN,NaN,NaN,NaN,NaN
3,matches_100,GET,/v1/players/175966938/matches,200,100,100.0,NaN,NaN,NaN,NaN,NaN
4,heroes,GET,/v1/players/175966938/heroes,200,47,NaN,NaN,NaN,NaN,NaN,NaN
5,hero_global_winrates,GET,/v1/heroes/winrates,200,50,50.0,10000.0,winRate,NaN,NaN,NaN
6,hero_builds_ogre_magi,GET,/v1/heroes/84/builds,200,1,10.0,1000.0,NaN,10000.0,NaN,NaN
7,achievements_all,GET,/v1/players/175966938/achievements,200,59,NaN,NaN,NaN,NaN,NaN,NaN
8,achievements_unlocked,GET,/v1/players/175966938/achievements,200,21,NaN,NaN,NaN,NaN,true,NaN
9,achievements_locked,GET,/v1/players/175966938/achievements,200,38,NaN,NaN,NaN,NaN,false,NaN
10,rating,GET,/v1/players/175966938/rating,200,1,NaN,NaN,NaN,NaN,NaN,NaN
11,style,GET,/v1/players/175966938/style,200,1,20.0,NaN,NaN,NaN,NaN,NaN
12,leaderboard,GET,/v1/leaderboard,200,1,50.0,NaN,NaN,NaN,NaN,overall

,name,method,path,status,items,params.limit,params.min_matches,params.order_by,params.match_limit,params.unlocked,params.metric
0,summary,GET,/v1/players/175966938/summary,200,1,NaN,NaN,NaN,NaN,NaN,NaN
1,breakdowns,GET,/v1/players/175966938/breakdowns,200,1,NaN,NaN,NaN,NaN,NaN,NaN
2,matches_20,GET,/v1/players/175966938/matches,200,20,20.0,NaN,NaN,NaN,NaN,NaN
3,matches_100,GET,/v1/players/175966938/matches,200,100,100.0,NaN,NaN,NaN,NaN,NaN
4,heroes,GET,/v1/players/175966938/heroes,200,47,NaN,NaN,NaN,NaN,NaN,NaN
5,hero_global_winrates,GET,/v1/heroes/winrates,200,50,50.0,10000.0,winRate,NaN,NaN,NaN
6,hero_builds_ogre_magi,GET,/v1/heroes/84/builds,200,1,10.0,1000.0,NaN,10000.0,NaN,NaN
7,achievements_all,GET,/v1/players/175966938/achievements,200,59,NaN,NaN,NaN,NaN,NaN,NaN
8,achievements_unlocked,GET,/v1/players/175966938/achievements,200,21,NaN,NaN,NaN,NaN,true,NaN
9,achievements_locked,GET,/v1/players/175966938/achievements,200,38,NaN,NaN,NaN,NaN,false,NaN
10,rating,GET,/v1/players/175966938/rating,200,1,NaN,NaN,NaN,NaN,NaN,NaN
11,style,GET,/v1/players/175966938/style,200,1,20.0,NaN,NaN,NaN,NaN,NaN
12,leaderboard,GET,/v1/leaderboard,200,1,50.0,NaN,NaN,NaN,NaN,overall

## 5. Summary: профиль, winrate, KDA, карточка

In [8]:
summary = api_snapshot["responses"]["summary"]

summary_core = {
    key: value
    for key, value in summary.items()
    if key not in {"card", "avatar"}
}
show_table("GET /summary: основные поля", summary_core)

card = summary["card"]
card_rows = [
    {"metric": row["label"], "score": row["value"], "overall": card["overall"], "position": card["position"]}
    for row in card["rows"]
]
show_table("Карточка IMP/FRM/FGT/SUR/OBJ/UTL", card_rows)

show_table("Source метрики карточки", card.get("source", {}))

## GET /summary: основные поля

,accountId,name,rankTier,leaderboardRank,lastRefreshedAt,matches,wins,losses,winRate,kills,deaths,assists,kda,recentForm,breakdowns.byGameMode,breakdowns.byRanked
0,175966938,АДМИРАЛ,63,None,2026-07-09T11:52:21.338336,101,55,46,54.5,745,874,1309,2.35,"[L, L, W, W, W, W, W, W, L, W]","[{'gameMode': 23, 'label': 'Turbo', 'matches':...","[{'bucket': 'ranked', 'label': 'Ranked', 'matc..."

## Карточка IMP/FRM/FGT/SUR/OBJ/UTL

  metric  score  overall position
0    IMP     73       75      OFF
1    FRM     92       75      OFF
2    FGT     83       75      OFF
3    SUR     59       75      OFF
4    OBJ     77       75      OFF
5    UTL     79       75      OFF

## Source метрики карточки

,winrate,recentWinrate,avgKills,avgDeaths,avgAssists,avgGpm,avgXpm,avgHeroDamage,avgTowerDamage,avgHealing,avgLastHits,roleWeights,limit
0,54.5,70.0,7.4,8.7,13.0,927.7,1571.9,26428,2992,865,158.0,OFF,500

,winrate,recentWinrate,avgKills,avgDeaths,avgAssists,avgGpm,avgXpm,avgHeroDamage,avgTowerDamage,avgHealing,avgLastHits,roleWeights,limit
0,54.5,70.0,7.4,8.7,13.0,927.7,1571.9,26428,2992,865,158.0,OFF,500

## 6. Breakdowns: режимы матчей и ranked/unranked

In [9]:
breakdowns = api_snapshot["responses"]["breakdowns"]

if pd is not None:
    show_table("GET /breakdowns: byGameMode", breakdowns.get("byGameMode", []), max_rows=50)
    show_table("GET /breakdowns: byRanked", breakdowns.get("byRanked", []), max_rows=10)
else:
    show_json("GET /breakdowns", breakdowns)

## GET /breakdowns: byGameMode

,gameMode,label,matches,wins,losses,winRate,kills,deaths,assists,kda,avgKills,avgDeaths,avgAssists
0,23,Turbo,65,38,27,58.5,452,514,738,2.32,7.0,7.9,11.4
1,22,Ranked All Pick,33,16,17,48.5,264,333,536,2.40,8.0,10.1,16.2
2,4,Single Draft,2,1,1,50.0,18,15,24,2.80,9.0,7.5,12.0
3,2,Captains Mode,1,0,1,0.0,11,12,11,1.83,11.0,12.0,11.0

## GET /breakdowns: byRanked

,bucket,label,matches,wins,losses,winRate,kills,deaths,assists,kda,avgKills,avgDeaths,avgAssists
0,ranked,Ranked,33,16,17,48.5,264,333,536,2.40,8.0,10.1,16.2
1,unranked,Unranked,68,39,29,57.4,481,541,773,2.32,7.1,8.0,11.4

## 7. Matches: последние матчи и агрегаты

In [ ]:
matches = api_snapshot["responses"]["matches_100"]

if pd is not None:
    matches_df = pd.DataFrame(matches)
    matches_df["duration"] = matches_df["durationSeconds"].map(duration_label)
    matches_df["kda"] = matches_df.apply(lambda row: kda(row.kills, row.deaths, row.assists), axis=1)
    matches_df["result"] = matches_df["won"].map({True: "WIN", False: "LOSS"})
    show_table("GET /matches?limit=100", matches_df)

    display(Markdown("### Агрегаты по матчам"))
    match_aggregates = {
        "matches": len(matches_df),
        "wins": int(matches_df["won"].sum()),
        "losses": int((~matches_df["won"]).sum()),
        "winRate": round(matches_df["won"].mean() * 100, 1),
        "avgKills": round(matches_df["kills"].mean(), 2),
        "avgDeaths": round(matches_df["deaths"].mean(), 2),
        "avgAssists": round(matches_df["assists"].mean(), 2),
        "avgKda": round(matches_df["kda"].mean(), 2),
        "avgGpm": round(matches_df["gpm"].mean(), 1),
        "avgXpm": round(matches_df["xpm"].mean(), 1),
        "avgHeroDamage": round(matches_df["heroDamage"].mean(), 0),
        "avgTowerDamage": round(matches_df["towerDamage"].mean(), 0),
        "avgHealing": round(matches_df["heroHealing"].mean(), 0),
        "maxKills": int(matches_df["kills"].max()),
        "maxGpm": int(matches_df["gpm"].max()),
        "maxHeroDamage": int(matches_df["heroDamage"].max()),
    }
    display(pd.DataFrame([match_aggregates]))
else:
    show_json("GET /matches?limit=100", matches)

## GET /matches?limit=100

,matchId,startedAt,durationSeconds,heroId,gameMode,gameModeName,lobbyType,rankedBucket,rankedLabel,won,...,gpm,xpm,heroDamage,towerDamage,heroHealing,lastHits,laneRole,duration,kda,result
0,8886131605,2026-07-07T21:28:23,2483,60,22,Ranked All Pick,7.0,ranked,Ranked,False,...,336,581,11064,26,0,120,None,41:23,0.92,LOSS
1,8886077137,2026-07-07T20:34:47,2579,84,22,Ranked All Pick,7.0,ranked,Ranked,True,...,650,762,23528,2944,0,189,None,42:59,2.42,WIN
2,8885808627,2026-07-07T17:03:21,1895,63,23,Turbo,0.0,unranked,Unranked,True,...,1807,2731,84610,11998,0,230,None,31:35,2.38,WIN
3,8885724269,2026-07-07T16:00:22,1191,99,23,Turbo,0.0,unranked,Unranked,True,...,1136,1476,13224,5370,0,116,None,19:51,7.00,WIN
4,8885652481,2026-07-07T15:12:21,2011,36,23,Turbo,0.0,unranked,Unranked,True,...,1747,2869,78860,3948,8289,240,None,33:31,2.64,WIN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,8636890026,2026-01-05T19:03:18,1407,126,23,Turbo,0.0,unranked,Unranked,False,...,887,1211,21322,357,0,89,None,23:27,1.50,LOSS
96,8636850122,2026-01-05T18:30:45,1372,30,23,Turbo,0.0,unranked,Unranked,True,...,670,1840,15006,464,5692,5,None,22:52,2.22,WIN
97,8636767166,2026-01-05T17:23:49,1351,79,23,Turbo,0.0,unranked,Unranked,True,...,1054,2106,18082,3424,0,74,None,22:31,3.50,WIN
98,8636725471,2026-01-05T16:51:04,1730,126,23,Turbo,0.0,unranked,Unranked,True,...,1283,2124,22750,6008,0,165,None,28:50,4.50,WIN
99,8625327611,2025-12-28T17:20:32,3497,29,22,Ranked All Pick,7.0,ranked,Ranked,True,...,600,1116,47371,3431,6239,362,None,58:17,3.93,WIN

### Агрегаты по матчам

,matches,wins,losses,winRate,avgKills,avgDeaths,avgAssists,avgKda,avgGpm,avgXpm,avgHeroDamage,avgTowerDamage,avgHealing,maxKills,maxGpm,maxHeroDamage
0,100,55,45,55.0,7.39,8.69,13.03,3.11,927.1,1570.1,26459.0,3015.0,874.0,18,1873,84610

## 8. Heroes: пул героев, winrate, KDA

In [10]:
heroes = api_snapshot["responses"]["heroes"]

if pd is not None:
    heroes_df = pd.DataFrame(heroes)
    heroes_df = heroes_df.sort_values(["games", "winRate", "kda"], ascending=[False, False, False])
    show_table("GET /heroes", heroes_df, max_rows=200)

    display(Markdown("### Топ героев по играм"))
    display(heroes_df[["heroId", "games", "wins", "losses", "winRate", "kda", "avgGpm", "avgXpm", "recentForm"]].head(15))

    display(Markdown("### Лучший winrate среди героев с 3+ играми"))
    display(heroes_df[heroes_df["games"] >= 3].sort_values(["winRate", "games"], ascending=[False, False]).head(15))
else:
    show_json("GET /heroes", heroes)

## GET /heroes

,heroId,games,wins,losses,winRate,avgKills,avgDeaths,avgAssists,kda,avgGpm,avgXpm,recentForm
0,60,17,8,9,47.1,9.2,8.1,13.3,2.80,657.1,1013.1,"[L, W, W, W, W]"
1,84,7,5,2,71.4,7.3,8.1,13.1,2.51,991.6,1655.1,"[W, W, L, L, W]"
2,126,6,1,5,16.7,7.2,9.0,6.8,1.56,940.3,1641.8,"[L, L, L, L, L]"
3,2,4,2,2,50.0,8.2,9.8,11.5,2.03,967.2,1657.8,"[W, L, L, W]"
4,101,3,3,0,100.0,12.7,10.0,11.3,2.40,1145.3,2056.0,"[W, W, W]"
8,28,3,2,1,66.7,7.7,8.3,19.7,3.28,893.0,1527.3,"[W, L, W]"
5,8,3,2,1,66.7,5.3,4.3,6.0,2.62,1342.0,2307.3,"[W, L, W]"
7,1,3,2,1,66.7,7.7,6.0,7.0,2.44,1312.3,2312.7,"[L, W, W]"
6,31,3,2,1,66.7,7.0,12.3,16.3,1.89,572.7,1081.3,"[W, L, W]"
10,36,3,1,2,33.3,12.3,10.7,12.0,2.28,977.7,1587.7,"[W, L, L]"
9,99,3,1,2,33.3,4.7,9.7,11.3,1.66,838.3,1188.0,"[W, L, L]"
11,86,2,2,0,100.0,10.0,9.0,19.0,3.22,892.0,1419.0,"[W, W]"
12,46,2,2,0,100.0,3.0,3.0,3.0,2.00,1417.0,1600.0,"[W, W]"
13,79,2,1,1,50.0,7.0,7.0,20.0,3.86,1136.0,2196.0,"[L, W]"
17,29,2,1,1,50.0,10.0,14.0,36.5,3.32,600.0,1093.0,"[L, W]"
14,54,2,1,1,50.0,6.5,5.5,10.0,3.00,1323.0,2206.5,"[L, W]"
15,75,2,1,1,50.0,7.0,9.0,16.5,2.61,1015.5,2374.0,"[W, L]"
16,135,2,1,1,50.0,6.5,11.0,16.5,2.09,519.0,721.0,"[L, W]"
18,106,2,0,2,0.0,6.0,9.0,12.0,2.00,897.5,1426.5,"[L, L]"
19,5,2,0,2,0.0,2.5,9.5,13.0,1.63,557.5,888.0,"[L, L]"
20,64,2,0,2,0.0,9.0,16.0,11.0,1.25,751.5,1165.0,"[L, L]"
29,108,1,1,0,100.0,7.0,2.0,13.0,10.00,1127.0,2005.0,[W]
25,35,1,1,0,100.0,11.0,3.0,9.0,6.67,622.0,655.0,[W]
33,121,1,1,0,100.0,5.0,5.0,25.0,6.00,375.0,485.0,[W]
35,102,1,1,0,100.0,10.0,5.0,17.0,5.40,1721.0,3002.0,[W]
24,123,1,1,0,100.0,6.0,6.0,17.0,3.83,1299.0,2501.0,[W]
34,10,1,1,0,100.0,8.0,5.0,11.0,3.80,1440.0,2578.0,[W]
28,33,1,1,0,100.0,1.0,7.0,21.0,3.14,878.0,2015.0,[W]
27,3,1,1,0,100.0,2.0,7.0,19.0,3.00,788.0,2374.0,[W]
30,104,1,1,0,100.0,7.0,8.0,14.0,2.62,989.0,2192.0,[W]
21,63,1,1,0,100.0,14.0,13.0,17.0,2.38,1807.0,2731.0,[W]
37,30,1,1,0,100.0,2.0,9.0,18.0,2.22,670.0,1840.0,[W]
22,42,1,1,0,100.0,4.0,5.0,7.0,2.20,1111.0,1810.0,[W]
23,25,1,1,0,100.0,5.0,9.0,13.0,2.00,1345.0,2266.0,[W]
32,47,1,1,0,100.0,4.0,8.0,12.0,2.00,519.0,597.0,[W]
31,57,1,1,0,100.0,3.0,8.0,12.0,1.88,1041.0,1893.0,[W]
36,103,1,1,0,100.0,5.0,12.0,7.0,1.00,1048.0,2055.0,[W]
26,52,1,1,0,100.0,2.0,15.0,12.0,0.93,1141.0,1677.0,[W]
46,91,1,0,1,0.0,3.0,6.0,20.0,3.83,831.0,2010.0,[L]
43,105,1,0,1,0.0,6.0,10.0,28.0,3.40,1215.0,1727.0,[L]
38,14,1,0,1,0.0,6.0,5.0,6.0,2.40,995.0,1746.0,[L]
44,11,1,0,1,0.0,7.0,9.0,7.0,1.56,1248.0,1540.0,[L]
39,69,1,0,1,0.0,6.0,12.0,11.0,1.42,532.0,697.0,[L]
45,98,1,0,1,0.0,9.0,12.0,7.0,1.33,1201.0,2239.0,[L]
40,110,1,0,1,0.0,7.0,12.0,7.0,1.17,999.0,1641.0,[L]
41,59,1,0,1,0.0,12.0,15.0,3.0,1.00,973.0,1412.0,[L]
42,27,1,0,1,0.0,2.0,9.0,5.0,0.78,703.0,1421.0,[L]

### Топ героев по играм

,heroId,games,wins,losses,winRate,kda,avgGpm,avgXpm,recentForm
0,60,17,8,9,47.1,2.80,657.1,1013.1,"[L, W, W, W, W]"
1,84,7,5,2,71.4,2.51,991.6,1655.1,"[W, W, L, L, W]"
2,126,6,1,5,16.7,1.56,940.3,1641.8,"[L, L, L, L, L]"
3,2,4,2,2,50.0,2.03,967.2,1657.8,"[W, L, L, W]"
4,101,3,3,0,100.0,2.40,1145.3,2056.0,"[W, W, W]"
8,28,3,2,1,66.7,3.28,893.0,1527.3,"[W, L, W]"
5,8,3,2,1,66.7,2.62,1342.0,2307.3,"[W, L, W]"
7,1,3,2,1,66.7,2.44,1312.3,2312.7,"[L, W, W]"
6,31,3,2,1,66.7,1.89,572.7,1081.3,"[W, L, W]"
10,36,3,1,2,33.3,2.28,977.7,1587.7,"[W, L, L]"
9,99,3,1,2,33.3,1.66,838.3,1188.0,"[W, L, L]"
11,86,2,2,0,100.0,3.22,892.0,1419.0,"[W, W]"
12,46,2,2,0,100.0,2.00,1417.0,1600.0,"[W, W]"
13,79,2,1,1,50.0,3.86,1136.0,2196.0,"[L, W]"
17,29,2,1,1,50.0,3.32,600.0,1093.0,"[L, W]"

### Лучший winrate среди героев с 3+ играми

,heroId,games,wins,losses,winRate,avgKills,avgDeaths,avgAssists,kda,avgGpm,avgXpm,recentForm
4,101,3,3,0,100.0,12.7,10.0,11.3,2.40,1145.3,2056.0,"[W, W, W]"
1,84,7,5,2,71.4,7.3,8.1,13.1,2.51,991.6,1655.1,"[W, W, L, L, W]"
8,28,3,2,1,66.7,7.7,8.3,19.7,3.28,893.0,1527.3,"[W, L, W]"
5,8,3,2,1,66.7,5.3,4.3,6.0,2.62,1342.0,2307.3,"[W, L, W]"
7,1,3,2,1,66.7,7.7,6.0,7.0,2.44,1312.3,2312.7,"[L, W, W]"
6,31,3,2,1,66.7,7.0,12.3,16.3,1.89,572.7,1081.3,"[W, L, W]"
3,2,4,2,2,50.0,8.2,9.8,11.5,2.03,967.2,1657.8,"[W, L, L, W]"
0,60,17,8,9,47.1,9.2,8.1,13.3,2.80,657.1,1013.1,"[L, W, W, W, W]"
10,36,3,1,2,33.3,12.3,10.7,12.0,2.28,977.7,1587.7,"[W, L, L]"
9,99,3,1,2,33.3,4.7,9.7,11.3,1.66,838.3,1188.0,"[W, L, L]"
2,126,6,1,5,16.7,7.2,9.0,6.8,1.56,940.3,1641.8,"[L, L, L, L, L]"

## 9. Global Heroes: общий STRATZ winrate

In [11]:
hero_global_winrates = api_snapshot["responses"]["hero_global_winrates"]

if pd is not None:
    hero_global_df = pd.DataFrame(hero_global_winrates)
    show_table("GET /v1/heroes/winrates", hero_global_df, max_rows=100)
else:
    show_json("GET /v1/heroes/winrates", hero_global_winrates)

## GET /v1/heroes/winrates

,heroId,name,displayName,shortName,imageUrl,roles,matchCount,winCount,lossCount,winRate
0,67,npc_dota_hero_spectre,Spectre,spectre,None,"[CARRY, ESCAPE, DURABLE]",155204,87256,67948,56.22
1,94,npc_dota_hero_medusa,Medusa,medusa,None,"[CARRY, DURABLE, DISABLER]",49930,27405,22525,54.89
2,12,npc_dota_hero_phantom_lancer,Phantom Lancer,phantom_lancer,None,"[CARRY, ESCAPE, NUKER, PUSHER]",131865,72110,59755,54.68
3,42,npc_dota_hero_skeleton_king,Wraith King,skeleton_king,None,"[CARRY, INITIATOR, DURABLE, DISABLER, SUPPORT]",154556,84066,70490,54.39
4,44,npc_dota_hero_phantom_assassin,Phantom Assassin,phantom_assassin,None,"[CARRY, ESCAPE]",184479,99381,85098,53.87
5,54,npc_dota_hero_life_stealer,Lifestealer,life_stealer,None,"[CARRY, ESCAPE, DURABLE, DISABLER]",126645,67832,58813,53.56
6,113,npc_dota_hero_arc_warden,Arc Warden,arc_warden,None,"[CARRY, ESCAPE, NUKER]",45330,24177,21153,53.34
7,20,npc_dota_hero_vengefulspirit,Vengeful Spirit,vengefulspirit,None,"[ESCAPE, NUKER, INITIATOR, DISABLER, SUPPORT]",176176,93739,82437,53.21
8,41,npc_dota_hero_faceless_void,Faceless Void,faceless_void,None,"[CARRY, ESCAPE, INITIATOR, DURABLE, DISABLER]",139705,74259,65446,53.15
9,80,npc_dota_hero_lone_druid,Lone Druid,lone_druid,None,"[CARRY, DURABLE, PUSHER]",24659,13055,11604,52.94
10,22,npc_dota_hero_zuus,Zeus,zuus,None,"[CARRY, NUKER]",254863,134879,119984,52.92
11,128,npc_dota_hero_snapfire,Snapfire,snapfire,None,"[ESCAPE, NUKER, DISABLER, SUPPORT]",257394,135976,121418,52.83
12,52,npc_dota_hero_leshrac,Leshrac,leshrac,None,"[CARRY, NUKER, DISABLER, SUPPORT, PUSHER]",21982,11585,10397,52.70
13,96,npc_dota_hero_centaur,Centaur Warrunner,centaur,None,"[ESCAPE, NUKER, INITIATOR, DURABLE, DISABLER]",73895,38906,34989,52.65
14,103,npc_dota_hero_elder_titan,Elder Titan,elder_titan,None,"[NUKER, INITIATOR, DURABLE, DISABLER]",12363,6504,5859,52.61
15,31,npc_dota_hero_lich,Lich,lich,None,"[NUKER, SUPPORT]",143299,75255,68044,52.52
16,121,npc_dota_hero_grimstroke,Grimstroke,grimstroke,None,"[ESCAPE, NUKER, DISABLER, SUPPORT]",85476,44768,40708,52.37
17,137,npc_dota_hero_primal_beast,Primal Beast,primal_beast,None,"[INITIATOR, DURABLE, DISABLER]",38722,20249,18473,52.29
18,74,npc_dota_hero_invoker,Invoker,invoker,None,"[CARRY, ESCAPE, NUKER, DISABLER, PUSHER]",239776,125282,114494,52.25
19,104,npc_dota_hero_legion_commander,Legion Commander,legion_commander,None,"[CARRY, NUKER, INITIATOR, DURABLE, DISABLER]",202333,105467,96866,52.13
20,2,npc_dota_hero_axe,Axe,axe,None,"[CARRY, INITIATOR, DURABLE, DISABLER]",269424,140421,129003,52.12
21,88,npc_dota_hero_nyx_assassin,Nyx Assassin,nyx_assassin,None,"[ESCAPE, NUKER, INITIATOR, DISABLER]",82119,42751,39368,52.06
22,9,npc_dota_hero_mirana,Mirana,mirana,None,"[CARRY, ESCAPE, NUKER, DISABLER, SUPPORT]",101727,52866,48861,51.97
23,82,npc_dota_hero_meepo,Meepo,meepo,None,"[CARRY, ESCAPE, NUKER, INITIATOR, DISABLER, PU...",18218,9468,8750,51.97
24,60,npc_dota_hero_night_stalker,Night Stalker,night_stalker,None,"[CARRY, NUKER, INITIATOR, DURABLE, DISABLER]",88620,46043,42577,51.96
25,92,npc_dota_hero_visage,Visage,visage,None,"[NUKER, DURABLE, DISABLER, SUPPORT, PUSHER]",16817,8726,8091,51.89
26,8,npc_dota_hero_juggernaut,Juggernaut,juggernaut,None,"[CARRY, ESCAPE, PUSHER]",186456,96691,89765,51.86
27,62,npc_dota_hero_bounty_hunter,Bounty Hunter,bounty_hunter,None,"[ESCAPE, NUKER]",56955,29536,27419,51.86
28,75,npc_dota_hero_silencer,Silencer,silencer,None,"[CARRY, NUKER, INITIATOR, DISABLER, SUPPORT]",157927,81840,76087,51.82
29,68,npc_dota_hero_ancient_apparition,Ancient Apparition,ancient_apparition,None,"[NUKER, DISABLER, SUPPORT]",91166,47170,43996,51.74
30,27,npc_dota_hero_shadow_shaman,Shadow Shaman,shadow_shaman,None,"[NUKER, INITIATOR, DISABLER, SUPPORT, PUSHER]",215108,111035,104073,51.62
31,28,npc_dota_hero_slardar,Slardar,slardar,None,"[CARRY, ESCAPE, INITIATOR, DURABLE, DISABLER]",97289,50131,47158,51.53
32,29,npc_dota_hero_tidehunter,Tidehunter,tidehunter,None,"[CARRY, NUKER, INITIATOR, DURABLE, DISABLER]",105681,54409,51272,51.48
33,95,npc_dota_hero_troll_warlord,Troll Warlord,troll_warlord,None,"[CARRY, DURABLE, DISABLER, PUSHER]",30920,15842,15078,51.24
34,4,npc_dota_hero_bloodseeker,Bloodseeker,bloodseeker,None,"[CARRY, NUKER, INITIATOR, DISABLER]",52116,26691,25425,51.21
35,89,npc_dota_hero_naga_siren,Naga Siren,naga_siren,None,"[CARRY, ESCAPE, INITIATOR, DISABLER, SUPPORT, ...",20373,10432,9941,51.21
36,107,npc_dota_hero_earth_spirit,Earth Spirit,earth_spirit,None,"[ESCAPE, NUKER, INITIATOR, DURABLE, DISABLER]",53158,27176,25982,51.12
37,3,npc_dota_hero_bane,Bane,bane,None,"[NUKER, DURABLE, DISABLER, SUPPORT]",51698,26412,25286,51.09
38,30,npc_dota_hero_witch_doctor,Witch Doctor,witch_doctor,None,"[NUKER, DISABLER, SUPPORT]",211072,107743,103329,51.05
39,33,npc_dota_hero_enigma,Enigma,enigma,None,"[INITIATOR, DISABLER, PUSHER]",46167,23570,22597,51.05
40,71,npc_dota_hero_spirit_breaker,Spirit Breaker,spirit_breaker,None,"[CARRY, ESCAPE, INITIATOR, DURABLE, DISABLER]",186768,95281,91487,51.02
41,5,npc_dota_hero_crystal_maiden,Crystal Maiden,crystal_maiden,None,"[NUKER, DISABLER, SUPPORT]",163949,83553,80396,50.96
42,78,npc_dota_hero_brewmaster,Brewmaster,brewmaster,None,"[CARRY, NUKER, INITIATOR, DURABLE, DISABLER]",19490,9927,9563,50.93
43,26,npc_dota_hero_lion,Lion,lion,None,"[NUKER, INITIATOR, DISABLER, SUPPORT]",346520,176302,170218,50.88
44,36,npc_dota_hero_necrolyte,Necrophos,necrolyte,None,"[CARRY, NUKER, DURABLE, DISABLER]",209684,106626,103058,50.85
45,32,npc_dota_hero_riki,Riki,riki,None,"[CARRY, ESCAPE, DISABLER]",71217,36158,35059,50.77
46,105,npc_dota_hero_techies,Techies,techies,None,"[NUKER, DISABLER]",131805,66873,64932,50.74
47,102,npc_dota_hero_abaddon,Abaddon,abaddon,None,"[CARRY, DURABLE, SUPPORT]",61285,31071,30214,50.70
48,135,npc_dota_hero_dawnbreaker,Dawnbreaker,dawnbreaker,None,"[CARRY, DURABLE]",116521,58868,57653,50.52
49,99,npc_dota_hero_bristleback,Bristleback,bristleback,None,"[CARRY, NUKER, INITIATOR, DURABLE]",125291,63243,62048,50.48

## 10. Hero Builds: метовые сборки STRATZ

In [12]:
hero_builds = api_snapshot["responses"]["hero_builds_ogre_magi"]

show_json("GET /v1/heroes/84/builds", {k: v for k, v in hero_builds.items() if k not in {"coreItems", "startingItems", "boots", "neutralItems", "talents", "skillBuild", "guides"}})

if pd is not None:
    for section in ["coreItems", "startingItems", "boots", "neutralItems", "talents", "skillBuild", "guides"]:
        display(Markdown(f"### {section}"))
        display(pd.json_normalize(hero_builds.get(section) or []).head(30))
else:
    show_json("Hero builds sections", hero_builds)

## GET /v1/heroes/84/builds

### coreItems

,itemId,itemName,shortName,matchCount,winCount,winRate,metaScore,averageTimeMinute,averageTimeSeconds,wasGiven,equippedMatchCount,equippedWinCount
0,65,Hand of Midas,hand_of_midas,182532,96396,52.81,83.48,16.3,None,None,None,None
1,88,Ring of Basilius,ring_of_basilius,150303,77897,51.83,71.66,5.3,None,None,None,None
2,36,Magic Wand,magic_wand,76131,39359,51.70,45.21,2.4,None,None,None,None
3,73,Bracer,bracer,28793,14564,50.58,27.96,1.5,None,None,None,None
4,178,Soul Ring,soul_ring,10022,5062,50.51,21.25,2.0,None,None,None,None

### startingItems

Empty DataFrame
Columns: []
Index: []

### boots

,itemId,itemName,shortName,matchCount,winCount,winRate,metaScore,averageTimeMinute,averageTimeSeconds,wasGiven,equippedMatchCount,equippedWinCount
0,180,Arcane Boots,arcane_boots,220932,113805,51.51,83.03,11.3,679.9,None,None,None
1,29,Boots of Speed,boots,77256,39456,51.07,40.60,7.1,427.0,None,None,None
2,231,Guardian Greaves,guardian_greaves,45516,28223,62.01,35.09,35.7,2144.5,None,None,None
3,48,Boots of Travel,travel_boots,23161,14919,64.41,29.36,36.5,2191.9,None,None,None
4,63,Power Treads,power_treads,25885,13104,50.62,25.33,12.6,753.0,None,None,None
5,220,Boots of Travel 2,travel_boots_2,1258,854,67.89,24.13,51.1,3067.8,None,None,None
6,931,Boots of Bearing,boots_of_bearing,1916,1237,64.56,23.16,34.6,2073.0,None,None,None
7,50,Phase Boots,phase_boots,10438,5249,50.29,20.67,12.1,727.1,None,None,None
8,214,Tranquil Boots,tranquil_boots,6948,3593,51.71,20.14,13.3,800.5,None,None,None

### neutralItems

Empty DataFrame
Columns: []
Index: []

### talents

,abilityId,abilityName,matchCount,winCount,winRate,metaScore,averageTimeMinute,averageTimeSeconds
0,403,+12 Ignite DPS,229615,117917,51.35,82.97,18.9,1134.3
1,6183,+35 Bloodlust Attack Speed,143614,79992,55.70,60.15,30.2,1810.0
2,442,+80 Damage,109300,59470,54.41,49.98,28.7,1723.6
3,6708,+30 Strength,99284,59847,60.28,49.20,36.9,2213.0
4,6707,+220 Fireblast Damage,74264,43999,59.25,41.76,36.7,2203.2
5,1181,+2/0.01 Dumb Luck Mana/Mana Regen Per Strength,55019,28219,51.29,33.53,19.2,1153.8
6,7030,17% Fireblast chance on attack,25937,16476,63.52,29.57,45.0,2698.3
7,730,special_bonus_attributes,20391,11003,53.96,24.66,24.6,1473.5

### skillBuild

,level,abilityId,abilityName,matchCount,winCount,winRate,metaScore
0,1,5439,Ignite,253610,129794,51.18,76.02
1,2,5438,Fireblast,230674,118386,51.32,70.81
2,3,5440,Bloodlust,21935,10876,49.58,22.38
3,4,5440,Bloodlust,90504,46555,51.44,38.74
4,5,5440,Bloodlust,9321,4632,49.69,19.53
5,6,5441,Multicast,283696,144835,51.05,82.87
6,7,5440,Bloodlust,15158,7705,50.83,21.26
7,8,5440,Bloodlust,27344,13902,50.84,24.06
8,9,5440,Bloodlust,15685,8109,51.70,21.69
9,10,403,+12 Ignite DPS,99304,50668,51.02,40.61
10,11,403,+12 Ignite DPS,124951,64642,51.73,46.73
11,12,403,+12 Ignite DPS,4011,2012,50.16,18.47
12,15,6183,+35 Bloodlust Attack Speed,2625,1162,44.27,16.10
13,16,6183,+35 Bloodlust Attack Speed,139269,77918,55.95,51.49
14,18,6183,+35 Bloodlust Attack Speed,1505,827,54.95,19.58
15,20,6708,+30 Strength,98293,59236,60.26,43.61
16,25,7030,17% Fireblast chance on attack,25865,16432,63.53,28.16
17,26,1181,+2/0.01 Dumb Luck Mana/Mana Regen Per Strength,24266,15472,63.76,27.88
18,27,6183,+35 Bloodlust Attack Speed,9388,6118,65.17,24.96
19,28,6707,+220 Fireblast Damage,4932,3273,66.36,24.36
20,29,7030,17% Fireblast chance on attack,1851,1220,65.91,23.49

### guides

,matchId,createdAt,itemIds,itemNames,neutralItemIds,neutralItemNames
0,8888708218,2026-07-09T19:47:02Z,[],[],[],[]
1,8888704788,2026-07-09T19:25:21Z,[],[],[],[]
2,8888630763,2026-07-09T18:34:28Z,[],[],[],[]
3,8888714232,2026-07-09T18:31:36Z,[],[],[],[]
4,8888637197,2026-07-09T18:30:43Z,[],[],[],[]
5,8888679610,2026-07-09T18:28:39Z,[],[],[],[]
6,8888616710,2026-07-09T18:26:06Z,[],[],[],[]
7,8888585822,2026-07-09T18:06:32Z,[],[],[],[]
8,8888596466,2026-07-09T17:56:35Z,[],[],[],[]
9,8888589789,2026-07-09T17:39:26Z,[],[],[],[]

## 11. Achievements: открытые, закрытые, прогресс

In [13]:
achievements = api_snapshot["responses"]["achievements_all"]
unlocked = api_snapshot["responses"]["achievements_unlocked"]
locked = api_snapshot["responses"]["achievements_locked"]

if pd is not None:
    achievement_columns = [
        "id",
        "title",
        "category",
        "tier",
        "progress",
        "target",
        "progressPercent",
        "unlocked",
        "unavailable",
        "evidence",
    ]

    def achievement_frame(items):
        rows = []
        for item in items:
            row = dict(item)
            row["evidence"] = json.dumps(row.get("evidence") or {}, ensure_ascii=False)
            rows.append(row)
        return pd.DataFrame(rows).reindex(columns=achievement_columns)

    achievements_df = achievement_frame(achievements)
    show_table("GET /achievements: все", achievements_df, max_rows=200)

    display(Markdown("### Открытые ачивки"))
    unlocked_df = achievement_frame(unlocked).sort_values(["category", "tier", "title"])
    display(unlocked_df[["id", "title", "category", "tier", "progress", "target", "progressPercent", "evidence"]].head(200))

    display(Markdown("### Ближайшие закрытые ачивки"))
    locked_df = achievement_frame(locked).sort_values("progressPercent", ascending=False)
    display(locked_df[["id", "title", "category", "tier", "progress", "target", "progressPercent", "unavailable", "evidence"]].head(25))

    display(Markdown("### Ачивки по категориям"))
    display(
        achievements_df.groupby(["category", "unlocked"])
        .size()
        .reset_index(name="count")
        .sort_values(["category", "unlocked"])
    )
else:
    show_json("GET /achievements", achievements)

## GET /achievements: все

,id,title,category,tier,progress,target,progressPercent,unlocked,unavailable,evidence
0,returning_player,Returning Player,activity,bronze,1.000000,1.0,100.0,True,False,"{""matchId"": 8669297557, ""gapDays"": 23, ""limit""..."
1,weekly_grinder,Weekly Grinder,activity,bronze,23.000000,10.0,100.0,True,False,"{""limit"": 500}"
2,marathon_day,Marathon Day,activity,silver,8.000000,5.0,100.0,True,False,"{""limit"": 500}"
3,chaos_enjoyer,Chaos Enjoyer,fun,bronze,6.000000,3.0,100.0,True,False,"{""limit"": 500}"
4,glass_cannon,Glass Cannon,fun,bronze,1.000000,1.0,100.0,True,False,"{""limit"": 500}"
5,anti_mage_afk_forest,"АФК лес, потом GG проебали",hero_flavor,gold,2.000000,10.0,20.0,False,False,"{""heroId"": 1, ""heroName"": ""Anti-Mage"", ""matchI..."
6,arc_warden_two_accounts,Два аккаунта в одной игре,hero_flavor,gold,0.000000,10.0,0.0,False,False,"{""heroId"": 113, ""heroName"": ""Arc Warden"", ""mat..."
7,broodmother_real_estate,Риэлтор паутины,hero_flavor,gold,0.000000,10.0,0.0,False,False,"{""heroId"": 61, ""heroName"": ""Broodmother"", ""mat..."
8,chen_zoo_director,Директор зоопарка,hero_flavor,gold,0.000000,5.0,0.0,False,False,"{""heroId"": 66, ""heroName"": ""Chen"", ""matchIds"":..."
9,clinkz_tower_arson,Поджог недвижимости,hero_flavor,gold,0.000000,10000.0,0.0,False,False,"{""heroId"": 56, ""heroName"": ""Clinkz"", ""matchIds..."
10,invoker_piano_without_notes,Пианист без нот,hero_flavor,gold,0.000000,10.0,0.0,False,False,"{""heroId"": 74, ""heroName"": ""Invoker"", ""matchId..."
11,io_ball_of_anxiety,Шар тревожности,hero_flavor,gold,0.000000,5.0,0.0,False,False,"{""heroId"": 91, ""heroName"": ""Io"", ""matchIds"": [..."
12,meepo_family_contract,Мобилизация чурок,hero_flavor,gold,0.000000,5.0,0.0,False,False,"{""heroId"": 82, ""heroName"": ""Meepo"", ""matchIds""..."
13,ogre_magi_ludik_ebanny,Лудик ебанный,hero_flavor,gold,42525.000000,30000.0,100.0,True,False,"{""heroId"": 84, ""heroName"": ""Ogre Magi"", ""match..."
14,phantom_assassin_crit_to_morale,Крит по морали,hero_flavor,gold,0.000000,10.0,0.0,False,False,"{""heroId"": 44, ""heroName"": ""Phantom Assassin"",..."
15,pudge_hookaholic,Хукоголик,hero_flavor,gold,0.000000,10.0,0.0,False,False,"{""heroId"": 14, ""heroName"": ""Pudge"", ""matchIds""..."
16,shadow_fiend_zxc_ministry,Неформал дед инсайд,hero_flavor,gold,0.000000,10.0,0.0,False,False,"{""heroId"": 11, ""heroName"": ""Shadow Fiend"", ""ma..."
17,storm_spirit_mana_credit,Мана в кредит,hero_flavor,gold,0.000000,10.0,0.0,False,False,"{""heroId"": 17, ""heroName"": ""Storm Spirit"", ""ma..."
18,tinker_button_maniac,Кнопочный душнила,hero_flavor,gold,0.000000,10.0,0.0,False,False,"{""heroId"": 34, ""heroName"": ""Tinker"", ""matchIds..."
19,zeus_damage_cloud,Облако с претензией,hero_flavor,gold,0.000000,45000.0,0.0,False,False,"{""heroId"": 22, ""heroName"": ""Zeus"", ""matchIds"":..."
20,techies_son_of_shahed,Сын шахеда,hero_flavor,legendary,0.000000,10.0,0.0,False,False,"{""heroId"": 105, ""heroName"": ""Techies"", ""matchI..."
21,alchemist_chemical_salary,Забрал пенсию у бабки,hero_flavor,silver,0.000000,10.0,0.0,False,False,"{""heroId"": 73, ""heroName"": ""Alchemist"", ""match..."
22,axe_spin_doctor,Вертушка судьбы,hero_flavor,silver,1.000000,10.0,10.0,False,False,"{""heroId"": 2, ""heroName"": ""Axe"", ""matchIds"": [..."
23,crystal_maiden_arcane_on_boots,Аркана на тапках,hero_flavor,silver,0.000000,10.0,0.0,False,False,"{""heroId"": 5, ""heroName"": ""Crystal Maiden"", ""m..."
24,dazzle_no_one_dies,"Никто не умер, я сказал",hero_flavor,silver,0.000000,5.0,0.0,False,False,"{""heroId"": 50, ""heroName"": ""Dazzle"", ""matchIds..."
25,earthshaker_echo_couch,Эхо с дивана,hero_flavor,silver,0.000000,10.0,0.0,False,False,"{""heroId"": 7, ""heroName"": ""Earthshaker"", ""matc..."
26,faceless_void_chrono_lawyer,Хуйсос безглазый,hero_flavor,silver,0.000000,10.0,0.0,False,False,"{""heroId"": 41, ""heroName"": ""Faceless Void"", ""m..."
27,huskar_low_hp_lifestyle,Жизнь на красном HP,hero_flavor,silver,0.000000,10.0,0.0,False,False,"{""heroId"": 59, ""heroName"": ""Huskar"", ""matchIds..."
28,juggernaut_spin_to_win,Крутилка без мыслей,hero_flavor,silver,1.000000,10.0,10.0,False,False,"{""heroId"": 8, ""heroName"": ""Juggernaut"", ""match..."
29,lion_finger_explained,Палец объяснил,hero_flavor,silver,0.000000,10.0,0.0,False,False,"{""heroId"": 26, ""heroName"": ""Lion"", ""matchIds"":..."
30,riki_where_is_detection,Где сентри?,hero_flavor,silver,0.000000,10.0,0.0,False,False,"{""heroId"": 32, ""heroName"": ""Riki"", ""matchIds"":..."
31,sniper_balcony_grandpa,Дед с хуем на балконе,hero_flavor,silver,1.000000,10.0,10.0,False,False,"{""heroId"": 35, ""heroName"": ""Sniper"", ""matchIds..."
32,ursa_roshan_landlord,Хозяин Рошпита,hero_flavor,silver,0.000000,10.0,0.0,False,False,"{""heroId"": 70, ""heroName"": ""Ursa"", ""matchIds"":..."
33,witch_doctor_maledict_enjoyer,Маледикт терапевт,hero_flavor,silver,1.000000,10.0,10.0,False,False,"{""heroId"": 30, ""heroName"": ""Witch Doctor"", ""ma..."
34,hero_spammer,Hero Spammer,hero_mastery,bronze,5.000000,10.0,50.0,False,False,"{""limit"": 500}"
35,cursed_breaker,Cursed Breaker,hero_mastery,gold,1.000000,1.0,100.0,True,False,"{""matchId"": 8848789080, ""heroId"": 60, ""limit"":..."
36,signature_hero,Signature Hero,hero_mastery,gold,0.784314,1.0,78.4,False,False,"{""heroId"": 60, ""games"": 17, ""wins"": 8, ""winRat..."
37,hero_loyalist,Hero Loyalist,hero_mastery,silver,17.000000,25.0,68.0,False,False,"{""limit"": 500}"
38,wide_pool,Wide Pool,hero_mastery,silver,35.000000,10.0,100.0,True,False,"{""heroIds"": [1, 2, 3, 8, 10, 25, 28, 29, 30, 3..."
39,kda_5,KDA Machine,performance,bronze,11.000000,5.0,100.0,True,False,"{""matchId"": 8848789080, ""limit"": 500}"
40,clean_game,Clean Game,performance,gold,1.000000,1.0,100.0,True,False,"{""matchId"": 8848789080, ""deaths"": 2, ""killPart..."
41,damage_dealer,Damage Dealer,performance,gold,84610.000000,40000.0,100.0,True,False,"{""matchId"": 8885808627, ""hero_damage"": 84610.0..."
42,tower_melter,Tower Melter,performance,gold,15436.000000,8000.0,100.0,True,False,"{""matchId"": 8883116792, ""tower_damage"": 15436...."
43,deathless_win,Deathless Win,performance,silver,0.000000,1.0,0.0,False,False,"{""limit"": 500}"
44,farming_machine,Farming Machine,performance,silver,1873.000000,700.0,100.0,True,False,"{""matchId"": 8669297557, ""gold_per_min"": 1873.0..."
45,healer,Healer,performance,silver,16564.000000,10000.0,100.0,True,False,"{""matchId"": 8704906930, ""hero_healing"": 16564...."
46,kda_10,KDA Monster,performance,silver,11.000000,10.0,100.0,True,False,"{""matchId"": 8848789080, ""limit"": 500}"
47,support_engine,Support Engine,performance,silver,45.000000,25.0,100.0,True,False,"{""matchId"": 8625327611, ""assists"": 45.0, ""limi..."
48,xp_machine,XP Machine,performance,silver,3412.000000,800.0,100.0,True,False,"{""matchId"": 8883799162, ""xp_per_min"": 3412.0, ..."
49,flex_player,Flex Player,role,gold,2.000000,3.0,66.7,False,False,"{""roles"": [""MID"", ""OFF""], ""limit"": 500}"
50,carry_core,Carry Core,role,silver,0.990000,1.0,99.0,False,False,"{""position"": ""OFF"", ""score"": 92, ""limit"": 500}"
51,mid_pressure,Mid Pressure,role,silver,0.990000,1.0,99.0,False,False,"{""position"": ""OFF"", ""score"": 83, ""limit"": 500}"
52,offlane_impact,Offlane Impact,role,silver,0.880000,1.0,88.0,False,False,"{""position"": ""OFF"", ""score"": 66.0, ""limit"": 500}"
53,support_brain,Support Brain,role,silver,0.990000,1.0,99.0,False,False,"{""position"": ""OFF"", ""score"": 79, ""limit"": 500}"
54,hot_streak_3,Hot Streak III,win_form,bronze,6.000000,3.0,100.0,True,False,"{""limit"": 500}"
55,hot_streak_10,Hot Streak X,win_form,gold,6.000000,10.0,60.0,False,False,"{""limit"": 500}"
56,clutch_late_game,Late Game Clutch,win_form,silver,1.000000,1.0,100.0,True,False,"{""limit"": 500}"
57,hot_streak_5,Hot Streak V,win_form,silver,6.000000,5.0,100.0,True,False,"{""limit"": 500}"
58,tilt_resistant,Tilt Resistant,win_form,silver,1.000000,1.0,100.0,True,False,"{""matchId"": 8841433476, ""limit"": 500}"

### Открытые ачивки

,id,title,category,tier,progress,target,progressPercent,evidence
0,returning_player,Returning Player,activity,bronze,1.0,1.0,100.0,"{""matchId"": 8669297557, ""gapDays"": 23, ""limit""..."
1,weekly_grinder,Weekly Grinder,activity,bronze,23.0,10.0,100.0,"{""limit"": 500}"
2,marathon_day,Marathon Day,activity,silver,8.0,5.0,100.0,"{""limit"": 500}"
3,chaos_enjoyer,Chaos Enjoyer,fun,bronze,6.0,3.0,100.0,"{""limit"": 500}"
4,glass_cannon,Glass Cannon,fun,bronze,1.0,1.0,100.0,"{""limit"": 500}"
5,ogre_magi_ludik_ebanny,Лудик ебанный,hero_flavor,gold,42525.0,30000.0,100.0,"{""heroId"": 84, ""heroName"": ""Ogre Magi"", ""match..."
6,cursed_breaker,Cursed Breaker,hero_mastery,gold,1.0,1.0,100.0,"{""matchId"": 8848789080, ""heroId"": 60, ""limit"":..."
7,wide_pool,Wide Pool,hero_mastery,silver,35.0,10.0,100.0,"{""heroIds"": [1, 2, 3, 8, 10, 25, 28, 29, 30, 3..."
8,kda_5,KDA Machine,performance,bronze,11.0,5.0,100.0,"{""matchId"": 8848789080, ""limit"": 500}"
9,clean_game,Clean Game,performance,gold,1.0,1.0,100.0,"{""matchId"": 8848789080, ""deaths"": 2, ""killPart..."
10,damage_dealer,Damage Dealer,performance,gold,84610.0,40000.0,100.0,"{""matchId"": 8885808627, ""hero_damage"": 84610.0..."
11,tower_melter,Tower Melter,performance,gold,15436.0,8000.0,100.0,"{""matchId"": 8883116792, ""tower_damage"": 15436...."
12,farming_machine,Farming Machine,performance,silver,1873.0,700.0,100.0,"{""matchId"": 8669297557, ""gold_per_min"": 1873.0..."
13,healer,Healer,performance,silver,16564.0,10000.0,100.0,"{""matchId"": 8704906930, ""hero_healing"": 16564...."
14,kda_10,KDA Monster,performance,silver,11.0,10.0,100.0,"{""matchId"": 8848789080, ""limit"": 500}"
15,support_engine,Support Engine,performance,silver,45.0,25.0,100.0,"{""matchId"": 8625327611, ""assists"": 45.0, ""limi..."
16,xp_machine,XP Machine,performance,silver,3412.0,800.0,100.0,"{""matchId"": 8883799162, ""xp_per_min"": 3412.0, ..."
17,hot_streak_3,Hot Streak III,win_form,bronze,6.0,3.0,100.0,"{""limit"": 500}"
19,hot_streak_5,Hot Streak V,win_form,silver,6.0,5.0,100.0,"{""limit"": 500}"
18,clutch_late_game,Late Game Clutch,win_form,silver,1.0,1.0,100.0,"{""limit"": 500}"
20,tilt_resistant,Tilt Resistant,win_form,silver,1.0,1.0,100.0,"{""matchId"": 8841433476, ""limit"": 500}"

### Ближайшие закрытые ачивки

,id,title,category,tier,progress,target,progressPercent,unavailable,evidence
36,support_brain,Support Brain,role,silver,0.990000,1.0,99.0,False,"{""position"": ""OFF"", ""score"": 79, ""limit"": 500}"
34,mid_pressure,Mid Pressure,role,silver,0.990000,1.0,99.0,False,"{""position"": ""OFF"", ""score"": 83, ""limit"": 500}"
33,carry_core,Carry Core,role,silver,0.990000,1.0,99.0,False,"{""position"": ""OFF"", ""score"": 92, ""limit"": 500}"
35,offlane_impact,Offlane Impact,role,silver,0.880000,1.0,88.0,False,"{""position"": ""OFF"", ""score"": 66.0, ""limit"": 500}"
29,signature_hero,Signature Hero,hero_mastery,gold,0.784314,1.0,78.4,False,"{""heroId"": 60, ""games"": 17, ""wins"": 8, ""winRat..."
30,hero_loyalist,Hero Loyalist,hero_mastery,silver,17.000000,25.0,68.0,False,"{""limit"": 500}"
32,flex_player,Flex Player,role,gold,2.000000,3.0,66.7,False,"{""roles"": [""MID"", ""OFF""], ""limit"": 500}"
37,hot_streak_10,Hot Streak X,win_form,gold,6.000000,10.0,60.0,False,"{""limit"": 500}"
28,hero_spammer,Hero Spammer,hero_mastery,bronze,5.000000,10.0,50.0,False,"{""limit"": 500}"
0,anti_mage_afk_forest,"АФК лес, потом GG проебали",hero_flavor,gold,2.000000,10.0,20.0,False,"{""heroId"": 1, ""heroName"": ""Anti-Mage"", ""matchI..."
25,sniper_balcony_grandpa,Дед с хуем на балконе,hero_flavor,silver,1.000000,10.0,10.0,False,"{""heroId"": 35, ""heroName"": ""Sniper"", ""matchIds..."
16,axe_spin_doctor,Вертушка судьбы,hero_flavor,silver,1.000000,10.0,10.0,False,"{""heroId"": 2, ""heroName"": ""Axe"", ""matchIds"": [..."
22,juggernaut_spin_to_win,Крутилка без мыслей,hero_flavor,silver,1.000000,10.0,10.0,False,"{""heroId"": 8, ""heroName"": ""Juggernaut"", ""match..."
27,witch_doctor_maledict_enjoyer,Маледикт терапевт,hero_flavor,silver,1.000000,10.0,10.0,False,"{""heroId"": 30, ""heroName"": ""Witch Doctor"", ""ma..."
10,shadow_fiend_zxc_ministry,Неформал дед инсайд,hero_flavor,gold,0.000000,10.0,0.0,False,"{""heroId"": 11, ""heroName"": ""Shadow Fiend"", ""ma..."
2,broodmother_real_estate,Риэлтор паутины,hero_flavor,gold,0.000000,10.0,0.0,False,"{""heroId"": 61, ""heroName"": ""Broodmother"", ""mat..."
3,chen_zoo_director,Директор зоопарка,hero_flavor,gold,0.000000,5.0,0.0,False,"{""heroId"": 66, ""heroName"": ""Chen"", ""matchIds"":..."
4,clinkz_tower_arson,Поджог недвижимости,hero_flavor,gold,0.000000,10000.0,0.0,False,"{""heroId"": 56, ""heroName"": ""Clinkz"", ""matchIds..."
5,invoker_piano_without_notes,Пианист без нот,hero_flavor,gold,0.000000,10.0,0.0,False,"{""heroId"": 74, ""heroName"": ""Invoker"", ""matchId..."
6,io_ball_of_anxiety,Шар тревожности,hero_flavor,gold,0.000000,5.0,0.0,False,"{""heroId"": 91, ""heroName"": ""Io"", ""matchIds"": [..."
31,deathless_win,Deathless Win,performance,silver,0.000000,1.0,0.0,False,"{""limit"": 500}"
7,meepo_family_contract,Мобилизация чурок,hero_flavor,gold,0.000000,5.0,0.0,False,"{""heroId"": 82, ""heroName"": ""Meepo"", ""matchIds""..."
8,phantom_assassin_crit_to_morale,Крит по морали,hero_flavor,gold,0.000000,10.0,0.0,False,"{""heroId"": 44, ""heroName"": ""Phantom Assassin"",..."
9,pudge_hookaholic,Хукоголик,hero_flavor,gold,0.000000,10.0,0.0,False,"{""heroId"": 14, ""heroName"": ""Pudge"", ""matchIds""..."
26,ursa_roshan_landlord,Хозяин Рошпита,hero_flavor,silver,0.000000,10.0,0.0,False,"{""heroId"": 70, ""heroName"": ""Ursa"", ""matchIds"":..."

### Ачивки по категориям

        category  unlocked  count
0       activity      True      3
1            fun      True      2
2    hero_flavor     False     28
3    hero_flavor      True      1
4   hero_mastery     False      3
5   hero_mastery      True      2
6    performance     False      1
7    performance      True      9
8           role     False      5
9       win_form     False      1
10      win_form      True      4

## 12. Achievements filters: категории и unlocked

In [14]:
categories = sorted({item["category"] for item in achievement_catalog})
category_responses = []

for category in categories:
    status, payload = api_request(
        "GET",
        f"/v1/players/{ACCOUNT_ID}/achievements",
        params={"category": category},
        allow_error=True,
    )
    category_responses.append({
        "category": category,
        "status": status,
        "items": len(payload) if isinstance(payload, list) else 0,
        "unlocked": sum(1 for item in payload if isinstance(payload, list) and item.get("unlocked")),
        "response": payload,
    })

show_table("GET /achievements?category=...", [{k: v for k, v in row.items() if k != "response"} for row in category_responses])

## GET /achievements?category=...

       category  status  items  unlocked
0      activity     200      3         3
1           fun     200      2         2
2   hero_flavor     200     29         1
3  hero_mastery     200      5         2
4   performance     200     10         9
5          role     200      5         0
6      win_form     200      5         4

       category  status  items  unlocked
0      activity     200      3         3
1           fun     200      2         2
2   hero_flavor     200     29         1
3  hero_mastery     200      5         2
4   performance     200     10         9
5          role     200      5         0
6      win_form     200      5         4

## 13. Rating: overall, role, breakdown

In [15]:
rating = api_snapshot["responses"]["rating"]
show_table("GET /rating: snapshot", {k: v for k, v in rating.items() if k not in {"breakdown", "source"}})

breakdown = rating.get("breakdown", {})
if isinstance(breakdown, dict):
    rows = breakdown.get("rows", breakdown)
else:
    rows = breakdown
show_table("Rating breakdown", rows)
show_table("Rating source", rating.get("source", {}))

## GET /rating: snapshot

   accountId  overall position                    createdAt
0  175966938       75      OFF  2026-07-09T20:45:54.919845Z

## Rating breakdown

  label  value
0   IMP     73
1   FRM     92
2   FGT     83
3   SUR     59
4   OBJ     77
5   UTL     79

## Rating source

,winrate,recentWinrate,avgKills,avgDeaths,avgAssists,avgGpm,avgXpm,avgHeroDamage,avgTowerDamage,avgHealing,avgLastHits,roleWeights,limit
0,54.5,70.0,7.4,8.7,13.0,927.7,1571.9,26428,2992,865,158.0,OFF,500

,winrate,recentWinrate,avgKills,avgDeaths,avgAssists,avgGpm,avgXpm,avgHeroDamage,avgTowerDamage,avgHealing,avgLastHits,roleWeights,limit
0,54.5,70.0,7.4,8.7,13.0,927.7,1571.9,26428,2992,865,158.0,OFF,500

## 14. Очки стиля за последние 100 матчей

In [ ]:
style_100 = api_snapshot["responses"]["style_100"]

if not isinstance(style_100, dict):
    show_json("GET /style?limit=100", style_100)
else:
    style_matches = pd.DataFrame(style_100.get("matches") or [])
    if style_matches.empty:
        display(Markdown("Нет матчей для расчета style score."))
    else:
        style_matches["score"] = pd.to_numeric(style_matches["score"], errors="coerce")
        style_matches["itemScore"] = pd.to_numeric(style_matches["itemScore"], errors="coerce")
        style_matches["skillScore"] = pd.to_numeric(style_matches["skillScore"], errors="coerce")
        rated_style = style_matches.dropna(subset=["score"]).copy()
        overview = pd.DataFrame([
            {
                "requestedMatches": style_100.get("matchesConsidered"),
                "ratedMatches": len(rated_style),
                "apiAverageStyle": style_100.get("styleScore"),
                "notebookAverageStyle": round(rated_style["score"].mean(), 1) if not rated_style.empty else None,
                "averageItems": round(rated_style["itemScore"].mean(), 1) if not rated_style.empty else None,
                "averageSkills": round(rated_style["skillScore"].mean(), 1) if not rated_style.empty else None,
                "label": style_100.get("label"),
            }
        ])
        show_table("Средний style score за 100 матчей", overview)

        by_hero = (
            rated_style.groupby(["heroId", "heroName"], dropna=False, as_index=False)
            .agg(
                matches=("matchId", "count"),
                averageStyle=("score", "mean"),
                averageItems=("itemScore", "mean"),
                averageSkills=("skillScore", "mean"),
                maxStyle=("score", "max"),
                minStyle=("score", "min"),
            )
            .sort_values(["averageStyle", "matches"], ascending=[False, False])
        )
        for column in ["averageStyle", "averageItems", "averageSkills", "maxStyle", "minStyle"]:
            by_hero[column] = by_hero[column].round(1)
        show_table("Style score по героям", by_hero, max_rows=200)
        display(Markdown("### Самые нестандартные матчи"))
        display(rated_style.sort_values("score", ascending=False)[["matchId", "heroId", "heroName", "score", "itemScore", "skillScore"]].head(20))

## 15. Leaderboard

In [ ]:
leaderboard = api_snapshot["responses"]["leaderboard"]
show_table("GET /v1/leaderboard?metric=overall&limit=50", leaderboard, max_rows=100)

## 15. Полный snapshot всех ответов

Переменная `api_snapshot` содержит все ответы. Следующая ячейка показывает верхний уровень и сохраняет JSON рядом с ноутбуком.

In [ ]:
snapshot_path = Path(f"api_snapshot_{ACCOUNT_ID}.json")
snapshot_path.write_text(json.dumps(api_snapshot, ensure_ascii=False, indent=2), encoding="utf-8")

display(Markdown(f"Saved snapshot: `{snapshot_path}`"))
show_json("api_snapshot", api_snapshot)